/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secapp;

import java.awt.Color;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;


/** 
 *
 * @author Dieudo M
 */
public class Home extends javax.swing.JFrame {
    
     GridBagLayout layout =  new GridBagLayout();
     static Completed_Tests completed;
     //static Available_tests completed;
     static Available_tests pending;
     static all_answers answers;
     static Pending_Tests pending_Tests;
    
     
     
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        //completed =  new Completed_Tests();
        completed =  new Completed_Tests();
        pending = new Available_tests();
       // answers =  new all_answers();
        pending_Tests = new Pending_Tests();
        mainPanel.setLayout(layout);
        // 75%
        GridBagConstraints c =  new GridBagConstraints();
        c.gridx =0;
        c.gridy=0;
        mainPanel.add(completed,c);
        c.gridx =0;
        c.gridy=0;
        //c.weightx =0.75;
        mainPanel.add(pending,c);
        c.gridx =0;
        c.gridy=0;
        //c.weightx =0.75;
        //mainPanel.add(answers,c);
        c.gridx =0;
        c.gridy=0;
         mainPanel.add(pending_Tests,c);
        c.gridx =0;
        c.gridy=0;
        pending_Tests.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane2 = new javax.swing.JPanel();
        competedArea = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        completedTest_btn = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        btn_admin = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        chat_btn = new javax.swing.JLabel();
        gradebook_area = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        gradebook_btn = new javax.swing.JLabel();
        pendingArea = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pendingTest_btn = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        horizontalBar = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bg.setBackground(new java.awt.Color(255, 255, 255));

        sidepane2.setBackground(new java.awt.Color(54, 33, 89));
        sidepane2.setPreferredSize(new java.awt.Dimension(250, 384));

        competedArea.setBackground(new java.awt.Color(54, 33, 89));
        competedArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                competedAreaMousePressed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secapp.dashboard.images/icons8_knowledge_sharing_30px.png"))); // NOI18N

        completedTest_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        completedTest_btn.setForeground(new java.awt.Color(204, 204, 204));
        completedTest_btn.setText("Completed Tests");
        completedTest_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                completedTest_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout competedAreaLayout = new javax.swing.GroupLayout(competedArea);
        competedArea.setLayout(competedAreaLayout);
        competedAreaLayout.setHorizontalGroup(
            competedAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(competedAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(completedTest_btn)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        competedAreaLayout.setVerticalGroup(
            competedAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, competedAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(competedAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(competedAreaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(completedTest_btn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("SECAPP");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_admin.setBackground(new java.awt.Color(54, 33, 89));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secapp.dashboard.images/icons8_chat_32px.png"))); // NOI18N

        chat_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chat_btn.setForeground(new java.awt.Color(204, 204, 204));
        chat_btn.setText("Chat ");

        javax.swing.GroupLayout btn_adminLayout = new javax.swing.GroupLayout(btn_admin);
        btn_admin.setLayout(btn_adminLayout);
        btn_adminLayout.setHorizontalGroup(
            btn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(chat_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_adminLayout.setVerticalGroup(
            btn_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(btn_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chat_btn))
        );

        gradebook_area.setBackground(new java.awt.Color(54, 33, 89));
        gradebook_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradebook_areaMouseClicked(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secapp.dashboard.images/icons8_report_card_80px.png"))); // NOI18N

        gradebook_btn.setBackground(new java.awt.Color(54, 33, 89));
        gradebook_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        gradebook_btn.setForeground(new java.awt.Color(204, 204, 204));
        gradebook_btn.setText("Grade Book");

        javax.swing.GroupLayout gradebook_areaLayout = new javax.swing.GroupLayout(gradebook_area);
        gradebook_area.setLayout(gradebook_areaLayout);
        gradebook_areaLayout.setHorizontalGroup(
            gradebook_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradebook_areaLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gradebook_btn)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        gradebook_areaLayout.setVerticalGroup(
            gradebook_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradebook_areaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gradebook_areaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gradebook_btn)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pendingArea.setBackground(new java.awt.Color(54, 33, 89));
        pendingArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingAreaMouseClicked(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/secapp.dashboard.images/icons8_knowledge_sharing_30px.png"))); // NOI18N

        pendingTest_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pendingTest_btn.setForeground(new java.awt.Color(204, 204, 204));
        pendingTest_btn.setText("Pending Tests");
        pendingTest_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pendingTest_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pendingAreaLayout = new javax.swing.GroupLayout(pendingArea);
        pendingArea.setLayout(pendingAreaLayout);
        pendingAreaLayout.setHorizontalGroup(
            pendingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pendingTest_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pendingAreaLayout.setVerticalGroup(
            pendingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pendingAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pendingTest_btn)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidepane2Layout = new javax.swing.GroupLayout(sidepane2);
        sidepane2.setLayout(sidepane2Layout);
        sidepane2Layout.setHorizontalGroup(
            sidepane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepane2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel17))
            .addGroup(sidepane2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(competedArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidepane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gradebook_area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pendingArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidepane2Layout.setVerticalGroup(
            sidepane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepane2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel17)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(competedArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pendingArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gradebook_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        horizontalBar.setBackground(new java.awt.Color(80, 50, 115));
        horizontalBar.setPreferredSize(new java.awt.Dimension(561, 50));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("SECAPP/");

        javax.swing.GroupLayout horizontalBarLayout = new javax.swing.GroupLayout(horizontalBar);
        horizontalBar.setLayout(horizontalBarLayout);
        horizontalBarLayout.setHorizontalGroup(
            horizontalBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horizontalBarLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(321, 321, 321))
        );
        horizontalBarLayout.setVerticalGroup(
            horizontalBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, horizontalBarLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addContainerGap())
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidepane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(horizontalBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(horizontalBar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sidepane2, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void completedTest_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completedTest_btnMouseClicked
        // TODO add your handling code here:
       // pendingArea.setBackground(Color.getHSBColor(54, 33, 89));
       
    }//GEN-LAST:event_completedTest_btnMouseClicked

    private void pendingTest_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingTest_btnMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pendingTest_btnMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void pendingAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pendingAreaMouseClicked
        // TODO add your handling code here:
        pendingArea.setBackground(new Color(126, 87, 194));
        competedArea.setBackground(new Color(54,33,89));
        gradebook_area.setBackground(new Color(54,33,89));
        //pending.setVisible(true);
         pending.setVisible(true);
         completed.setVisible(false);
         answers.setVisible(false);
         pending_Tests.setVisible(false);
    }//GEN-LAST:event_pendingAreaMouseClicked

    private void gradebook_areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradebook_areaMouseClicked
        // TODO add your handling code here:
        gradebook_area.setBackground(new Color(126, 87, 194));
        competedArea.setBackground(new Color(54,33,89));
        pendingArea.setBackground(new Color(54,33,89));
        
    }//GEN-LAST:event_gradebook_areaMouseClicked

    private void competedAreaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_competedAreaMousePressed
        // TODO add your handling code here:
         competedArea.setBackground(new Color(126, 87, 194));
        pendingArea.setBackground(new Color(54,33,89));
        completed.setVisible(true);
        pending.setVisible(false);
       answers.setVisible(false);
       pending_Tests.setVisible(false);
       
    }//GEN-LAST:event_competedAreaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
                   completed.setVisible(false);
                pending.setVisible(false);
                //answers.setVisible(false);
                pending_Tests.setVisible(false);
                home.setVisible(true);
                home.setUndecorated(true);
                home.setExtendedState(MAXIMIZED_BOTH);
              
                 
    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btn_admin;
    private javax.swing.JLabel chat_btn;
    private javax.swing.JPanel competedArea;
    private javax.swing.JLabel completedTest_btn;
    private javax.swing.JPanel gradebook_area;
    private javax.swing.JLabel gradebook_btn;
    private javax.swing.JPanel horizontalBar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pendingArea;
    private javax.swing.JLabel pendingTest_btn;
    private javax.swing.JPanel sidepane2;
    // End of variables declaration//GEN-END:variables
}

