/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secapp;

import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Projections;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import org.bson.Document;
import static secapp.Home.answers;
import static secapp.Home.completed;

/**
 *
 * @author Dieudo M
 */
public class Pending_Tests extends javax.swing.JPanel {
    
    int Min, Sec;
     private Timer timer;
    private int[] time;
    final int MIN = 0;
    final int SEC = 1;
    static Pending_Tests pending;
     static all_answers answers;
   

    /**
     * Creates new form Pending_Tests
     */
    public Pending_Tests() {
        initComponents();
        btnPrevious.setVisible(false);
        //completed =  new Completed_Tests();
        GridBagLayout layout =  new GridBagLayout();
        //completed =  new Completed_Tests();
        //pending = new Pending_Tests();
        answers =  new all_answers();
        questionDisplay.setLayout(layout);
        // 75%
        GridBagConstraints c =  new GridBagConstraints();
        c.gridx =0;
        c.gridy=0;
        questionDisplay.add(answers,c);
        c.gridx =0;
        c.gridy=0;
        
        
    }
    // TIMER IMPLEMENTATION
     /*public JPanel addText(){
        //count = new JLabel();
        count.setFont(new Font("Arial Black", Font.BOLD, 25));
        //count.setHorizontalAlignment(SwingConstants.CENTER);
        count.setBackground(Color.RED);
        //message = new JLabel();
        message.setFont(new Font("Arial Black", Font.BOLD, 15));
        //JPanel panel = new JPanel(new GridLayout(2,1));
        //panel.add(count);
        //panel.add(message);
        //panel.setBackground(Color.WHITE);
        //message.setHorizontalAlignment(SwingConstants.CENTER);
        //return panel;
    }*/
     public void displayTime(int min, int sec){
        String minute = String.format("%02d",min);
        String second = (String.format("%02d",sec));
        count.setText(minute + ":" + second);
    }
     public void startCountdown(String time, String message){
        this.time = convertTimeToInt(time.split(":"));
        this.message.setText(message);
        count.setText(time);
        timer = new Timer(1000,new TimerListener());
        timer.setRepeats(true);
        timer.start();

    }
     public int[] convertTimeToInt(String[] time){
        int[] converted = new int[time.length];
        for(int i = 0; i<time.length; i++){
            converted[i] = Integer.valueOf(time[i]);
        }
        return converted;
    }
     private class TimerListener implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            if(time[MIN] == 0 && (time[SEC] == 1 || time[SEC] == 0)){
                count.setText("");
                message.setText("END");
                timer.stop();
            }else if(time[SEC] > 0){
                time[SEC] -= 1;
                displayTime(time[MIN], time[SEC]);
            }else if(time[SEC] == 0){
                time[SEC] = 59;
                time[MIN] -= 1;
                displayTime(time[MIN], time[SEC]);
            }

            count.setForeground(time[MIN] == 0 && time[SEC] >= 6 ? Color.BLACK : Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionDisplay = new javax.swing.JPanel();
        questions = new javax.swing.JPanel();
        questionNumber = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        question_area = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        answer_area = new javax.swing.JTextField();
        submit_btn = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        count = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        q1_btn = new javax.swing.JButton();
        q2_btn = new javax.swing.JButton();
        q3_btn = new javax.swing.JButton();
        q4_btn = new javax.swing.JButton();
        btn_finish = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        questionDisplay.setBackground(new java.awt.Color(255, 255, 255));

        questions.setBackground(new java.awt.Color(255, 255, 255));

        questionNumber.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        questionNumber.setText("Question 1/4");

        question_area.setEditable(false);
        question_area.setColumns(20);
        question_area.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        question_area.setRows(5);
        question_area.setText("\"Running a\n program on a super computer with a certain amount of ressources \ndoes not garanty high performance \"Explain");
        jScrollPane1.setViewportView(question_area);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Answer");

        answer_area.setText("Type your answer here.....");
        answer_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_areaActionPerformed(evt);
            }
        });

        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(54, 33, 89));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(54, 33, 89));
        btnPrevious.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevious.setText("<Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        count.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        count.setText("0:0");

        message.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        message.setText("Message");

        q1_btn.setBackground(new java.awt.Color(54, 33, 89));
        q1_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q1_btn.setForeground(new java.awt.Color(255, 255, 255));
        q1_btn.setText("Q1");
        q1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_btnActionPerformed(evt);
            }
        });

        q2_btn.setBackground(new java.awt.Color(54, 33, 89));
        q2_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q2_btn.setForeground(new java.awt.Color(255, 255, 255));
        q2_btn.setText("Q2");
        q2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_btnActionPerformed(evt);
            }
        });

        q3_btn.setBackground(new java.awt.Color(54, 33, 89));
        q3_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q3_btn.setForeground(new java.awt.Color(255, 255, 255));
        q3_btn.setText("Q3");
        q3_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_btnActionPerformed(evt);
            }
        });

        q4_btn.setBackground(new java.awt.Color(54, 33, 89));
        q4_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        q4_btn.setForeground(new java.awt.Color(255, 255, 255));
        q4_btn.setText("Q4");
        q4_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_btnActionPerformed(evt);
            }
        });

        btn_finish.setBackground(new java.awt.Color(54, 33, 89));
        btn_finish.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_finish.setForeground(new java.awt.Color(255, 255, 255));
        btn_finish.setText("Finish");
        btn_finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionsLayout = new javax.swing.GroupLayout(questions);
        questions.setLayout(questionsLayout);
        questionsLayout.setHorizontalGroup(
            questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionsLayout.createSequentialGroup()
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(questionsLayout.createSequentialGroup()
                                .addComponent(questionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(441, 441, 441)
                                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(message)
                                    .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(questionsLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(answer_area, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(questionsLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext))))
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(q1_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(q2_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(q3_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(q4_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(submit_btn)
                        .addGap(69, 69, 69)
                        .addComponent(btn_finish)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        questionsLayout.setVerticalGroup(
            questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsLayout.createSequentialGroup()
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(count, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(message))
                    .addGroup(questionsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(questionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1_btn)
                    .addComponent(q2_btn)
                    .addComponent(q3_btn)
                    .addComponent(q4_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsLayout.createSequentialGroup()
                        .addComponent(btnPrevious)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsLayout.createSequentialGroup()
                        .addComponent(btnNext)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(answer_area, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(questionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_finish)
                            .addComponent(submit_btn))))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout questionDisplayLayout = new javax.swing.GroupLayout(questionDisplay);
        questionDisplay.setLayout(questionDisplayLayout);
        questionDisplayLayout.setHorizontalGroup(
            questionDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionDisplayLayout.createSequentialGroup()
                .addComponent(questions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        questionDisplayLayout.setVerticalGroup(
            questionDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionDisplayLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(questions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(questionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(questionDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // THIS ARE THE CONNECTION DETAILS TO MONGODB.... needs to be put in a public method
    //public static void connectionMongo (){
        int port_no = 27017;
	String host_name = "localhost", db_name = "SECAPP", db_coll_name = "testa";
        String client_url = "mongodb://" + host_name + ":" + port_no + "/" + db_name;
        MongoClientURI uri = new MongoClientURI(client_url);
    MongoClient mongo_client = new MongoClient(uri);
    MongoDatabase db = mongo_client.getDatabase(db_name);
                MongoCollection<Document> coll = db.getCollection(db_coll_name);
        
    //}
    
                // Fetching the database from the mongodb.
                
		
    
    
    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        // TODO add your handling code here:
     
        String questionNum = questionNumber.getText();
        String answer = answer_area.getText();
        
        //String Q_number = questionNumber.getText();
        //MongoDemo demo = new MongoDemo();
        //demo.main(new String[0]);
        // Connecting to the mongodb server using the given client uri.
		
                
                // Adding a single document in the mongo collection.
		Document emp1 = new Document();
		//emp1.put("name", "Coding is Fun");
		//emp1.put("website", "WE FUCKIT.com");
                emp1.put("answer",answer );
                emp1.put ("Qno",questionNum);
                coll.insertOne(emp1);
          
                // fetchin data from the Students collections
                
                FindIterable<Document> fi = coll.find();
                MongoCursor<Document> cursor = fi.iterator();
                
                /*try {
			while(cursor.hasNext()) {
				//log.info(cursor.next().toJson());
                                
                                 Map<String, Object> document = cursor.next();
                     	}
		} finally {
			cursor.close();
		}*/
        
    }//GEN-LAST:event_submit_btnActionPerformed

    private void q1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_btnActionPerformed
        // TODO add your handling code here:
        //String value  = coll.find().projection(Projections.include("answer")).first().getString("answer"); // Optiom 1
        //question_area.setText(value);
       
        
    }//GEN-LAST:event_q1_btnActionPerformed

    private void q2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_btnActionPerformed
        // TODO add your handling code here:
        String question2 =  "This is question two";
        question_area.setText(question2);
    }//GEN-LAST:event_q2_btnActionPerformed

    private void q3_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_btnActionPerformed
        // TODO add your handling code here:
        String question3 =  "This is question three";
        question_area.setText(question3);
    }//GEN-LAST:event_q3_btnActionPerformed

    private void q4_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_btnActionPerformed
        // TODO add your handling code here:
        String question4 =  "This is question four";
        question_area.setText(question4);
    }//GEN-LAST:event_q4_btnActionPerformed

    private void answer_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_areaActionPerformed
    static String question1,answer1;
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        btnNext.setVisible(false);
        question1 = question_area.getText();
        answer1 = answer_area.getText();
        questions.setVisible(true);
        questionNumber.setText("Question 2/2");
        //question_area.setText("");
        question_area.setText(" This is the second Test");
        btnPrevious.setVisible(true);
        btn_finish.setVisible(true);
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        questions.setVisible(true);
         questionNumber.setText("Question 1/2");
        String q2 = q2_btn.getText();
        String answer2 = question_area.getText();
        question_area.setText(question1);
        answer_area.setText(answer1);
       btnNext.setVisible(true);
        
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btn_finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finishActionPerformed
        // TODO add your handling code here:
        String q2 = q2_btn.getText();
        String answer2 = question_area.getText();
       //questionDisplay.setVisible(false);
       //all_answers answers = new all_answers();
       questions.setVisible(false);
       answers.setVisible(true);
               
      
        
        
    }//GEN-LAST:event_btn_finishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer_area;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btn_finish;
    private javax.swing.JLabel count;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JButton q1_btn;
    private javax.swing.JButton q2_btn;
    private javax.swing.JButton q3_btn;
    private javax.swing.JButton q4_btn;
    private javax.swing.JPanel questionDisplay;
    private javax.swing.JLabel questionNumber;
    private javax.swing.JTextArea question_area;
    private javax.swing.JPanel questions;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
